from typing import TypedDict, List, Dict, Any

class EvidenceItem(TypedDict):
    """The central object of the epistemic engine."""
    source_id: str        # Unique identifier for referencing (e.g., "src_001")
    title: str            # Title of paper, documentation page, or article
    url: str              # Source URL or DOI identifier
    content: str          # Raw or extracted text snippet containing the substance
    domain: str           # Extracted domain (empirical, interpretive, mixed)

class ExtractedClaim(TypedDict):
    """A granular point extracted directly from an EvidenceItem."""
    claim_id: str
    claim: str
    source_id: str        # Direct lineage linking the claim back to its primary evidence
    context: str          # Surrounding context from the text to verify logic

class CritiquedClaims(TypedDict):
    """The Claim Critic's exact categorical classifications."""
    SUPPORTED: List[ExtractedClaim]
    CONFLICTING: List[Dict[str, Any]]  # Maps conflicting views, positions, and sources
    INSUFFICIENT_EVIDENCE: List[ExtractedClaim]
    HYPOTHESIS: List[ExtractedClaim]

class ResearchGap(TypedDict):
    """A discovered open challenge or research limitation."""
    gap_description: str
    supporting_sources: List[str]  # List of source_ids identifying the gap
    gap_type: str                  # Enforced classification: "Strong" (2+ sources) or "Tentative"

class HypothesisItem(TypedDict):
    """A novel inference generated strictly from evidence patterns."""
    hypothesis: str
    rationale: str
    linked_evidence_ids: List[str]  # The foundational data points giving rise to this hypothesis

class ValidationReport(TypedDict):
    """The audit trail generated by the Validator before writing."""
    is_valid: bool
    traceability_passed: bool
    unsupported_claims_removed: bool
    uncertainty_calibrated: bool
    errors_found: List[str]

class EpistemicState(TypedDict):
    """The global, immutable state tracking schema for the LangGraph workflow."""
    query: str
    plan: List[str]
    evidence: List[EvidenceItem]
    extracted_claims: List[ExtractedClaim]
    critiqued_claims: CritiquedClaims
    supported_claims: List[ExtractedClaim]
    conflicting_claims: List[Dict[str, Any]]
    unsupported_claims: List[ExtractedClaim]
    gaps: List[ResearchGap]
    hypotheses: List[HypothesisItem]
    validation_status: ValidationReport
    final_report: str
    research_iterations: int